using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Northwind{
    public partial class SPs{
        
        /// <summary>
        /// Creates an object wrapper for the CustOrderHist Procedure
        /// </summary>
        public static StoredProcedure CustOrderHist(string CustomerID)
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("CustOrderHist", DataService.GetInstance("Northwind"), "dbo");
        	
            sp.Command.AddParameter("@CustomerID", CustomerID, DbType.String, null, null);
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the CustOrdersDetail Procedure
        /// </summary>
        public static StoredProcedure CustOrdersDetail(int? OrderID)
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("CustOrdersDetail", DataService.GetInstance("Northwind"), "dbo");
        	
            sp.Command.AddParameter("@OrderID", OrderID, DbType.Int32, 0, 10);
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the CustOrdersOrders Procedure
        /// </summary>
        public static StoredProcedure CustOrdersOrders(string CustomerID)
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("CustOrdersOrders", DataService.GetInstance("Northwind"), "dbo");
        	
            sp.Command.AddParameter("@CustomerID", CustomerID, DbType.String, null, null);
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the Employee Sales by Country Procedure
        /// </summary>
        public static StoredProcedure EmployeeSalesByCountry(DateTime? BeginningDate, DateTime? EndingDate)
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("Employee Sales by Country", DataService.GetInstance("Northwind"), "dbo");
        	
            sp.Command.AddParameter("@Beginning_Date", BeginningDate, DbType.DateTime, null, null);
        	
            sp.Command.AddParameter("@Ending_Date", EndingDate, DbType.DateTime, null, null);
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the Sales by Year Procedure
        /// </summary>
        public static StoredProcedure SalesByYear(DateTime? BeginningDate, DateTime? EndingDate)
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("Sales by Year", DataService.GetInstance("Northwind"), "dbo");
        	
            sp.Command.AddParameter("@Beginning_Date", BeginningDate, DbType.DateTime, null, null);
        	
            sp.Command.AddParameter("@Ending_Date", EndingDate, DbType.DateTime, null, null);
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the SalesByCategory Procedure
        /// </summary>
        public static StoredProcedure SalesByCategory(string CategoryName, string OrdYear)
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("SalesByCategory", DataService.GetInstance("Northwind"), "dbo");
        	
            sp.Command.AddParameter("@CategoryName", CategoryName, DbType.String, null, null);
        	
            sp.Command.AddParameter("@OrdYear", OrdYear, DbType.String, null, null);
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the Ten Most Expensive Products Procedure
        /// </summary>
        public static StoredProcedure TenMostExpensiveProducts()
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("Ten Most Expensive Products", DataService.GetInstance("Northwind"), "");
        	
            return sp;
        }
        
    }
    
}
