//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubSonic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SubSonic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ////// &lt;summary&gt;
        ////// Strongly-typed collection for the #CLASSNAME# class.
        ////// &lt;/summary&gt;
        ///[Serializable]
        ///public class #CLASSNAME#Collection : ActiveList&lt;#CLASSNAME#&gt; { }
        ///
        ////// &lt;summary&gt;
        ////// This is an ActiveRecord class which wraps the #TABLENAME# table.
        ////// &lt;/summary&gt;
        ///[Serializable]
        ///public class #CLASSNAME# : ActiveRecord&lt;#CLASSNAME#&gt; {
        ///    
        ///    #region Default Settings
        ///    void SetSQLProps() {
        ///        if (Table == null)
        ///            Table = Query.BuildTableSchema(&quot;#TABLENAME#&quot;);
        ///    }
        ///    #en [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CSharpClass {
            get {
                return ResourceManager.GetString("CSharpClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Text;
        ///using System.Data;
        ///using System.Data.SqlClient;
        ///using System.Data.Common;
        ///using System.Collections;
        ///using System.Collections.Generic;
        ///using System.Configuration;
        ///using System.Xml;
        ///using System.Xml.Serialization;
        ///using SubSonic;.
        /// </summary>
        internal static string CSharpClassUsing {
            get {
                return ResourceManager.GetString("CSharpClassUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///          /// &lt;summary&gt;
        ///          /// Inserts a record, can be used with the Object Data Source
        ///         /// &lt;/summary&gt;
        ///          public static void Insert(#ARGLIST#)  {
        ///                 #CLASSNAME# item=new #CLASSNAME#();
        ///                 #SETLIST#
        ///                 item.Save(System.Web.HttpContext.Current.User.Identity.Name);
        ///           }
        ///.
        /// </summary>
        internal static string CSharpODSInsert {
            get {
                return ResourceManager.GetString("CSharpODSInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///          /// &lt;summary&gt;
        ///          /// Updates a record, can be used with the Object Data Source
        ///         /// &lt;/summary&gt;
        ///          public static void Update(#ARGLIST#)  {
        ///                 #CLASSNAME# item=new #CLASSNAME#();
        ///                 #SETLIST#
        ///                 item.IsNew=false;
        ///                 item.Save(System.Web.HttpContext.Current.User.Identity.Name);
        ///           }
        ///.
        /// </summary>
        internal static string CSharpODSUpdate {
            get {
                return ResourceManager.GetString("CSharpODSUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     [XmlAttribute(&quot;#PROPNAME#&quot;)]
        ///    public #PROPTYPE# #PROPNAME# {
        ///        get {
        ///#GETTER#
        ///        }
        ///        set {
        ///#SETTER
        ///        }
        ///    }.
        /// </summary>
        internal static string CSharpProperty {
            get {
                return ResourceManager.GetString("CSharpProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to             /// &lt;summary&gt;
        ///            /// Executes the #SPNAME# Stored Procedure and returns an IDataReader.
        ///            /// &lt;/summary&gt;
        ///            public static IDataReader #METHODNAME#(#ARGLIST#){;
        ///                QueryCommand cmd=new QueryCommand(&quot;#SPNAME#&quot;);
        ///                cmd.CommandType=CommandType.StoredProcedure;
        ///                #PARAMS#
        ///                return DataService.GetReader(cmd);
        ///            }.
        /// </summary>
        internal static string CSharpSP {
            get {
                return ResourceManager.GetString("CSharpSP", resourceCulture);
            }
        }
    }
}
