using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Northwind
{
	#region Tables Struct
	public partial struct Tables
	{
		
		public static readonly string Category = @"Categories";
        
		public static readonly string CustomerCustomerDemo = @"CustomerCustomerDemo";
        
		public static readonly string CustomerDemographic = @"CustomerDemographics";
        
		public static readonly string Customer = @"Customers";
        
		public static readonly string Employee = @"Employees";
        
		public static readonly string EmployeeTerritory = @"EmployeeTerritories";
        
		public static readonly string OrderDetail = @"Order Details";
        
		public static readonly string Order = @"Orders";
        
		public static readonly string Product = @"Products";
        
		public static readonly string Region = @"Region";
        
		public static readonly string Shipper = @"Shippers";
        
		public static readonly string SubSonicTest = @"SubSonicTests";
        
		public static readonly string Supplier = @"Suppliers";
        
		public static readonly string Territory = @"Territories";
        
	}
	#endregion
    #region Schemas
    public partial class Schemas {
		
		public static TableSchema.Table Category
		{
            get { return DataService.GetSchema("Categories", "Northwind"); }
		}
        
		public static TableSchema.Table CustomerCustomerDemo
		{
            get { return DataService.GetSchema("CustomerCustomerDemo", "Northwind"); }
		}
        
		public static TableSchema.Table CustomerDemographic
		{
            get { return DataService.GetSchema("CustomerDemographics", "Northwind"); }
		}
        
		public static TableSchema.Table Customer
		{
            get { return DataService.GetSchema("Customers", "Northwind"); }
		}
        
		public static TableSchema.Table Employee
		{
            get { return DataService.GetSchema("Employees", "Northwind"); }
		}
        
		public static TableSchema.Table EmployeeTerritory
		{
            get { return DataService.GetSchema("EmployeeTerritories", "Northwind"); }
		}
        
		public static TableSchema.Table OrderDetail
		{
            get { return DataService.GetSchema("Order Details", "Northwind"); }
		}
        
		public static TableSchema.Table Order
		{
            get { return DataService.GetSchema("Orders", "Northwind"); }
		}
        
		public static TableSchema.Table Product
		{
            get { return DataService.GetSchema("Products", "Northwind"); }
		}
        
		public static TableSchema.Table Region
		{
            get { return DataService.GetSchema("Region", "Northwind"); }
		}
        
		public static TableSchema.Table Shipper
		{
            get { return DataService.GetSchema("Shippers", "Northwind"); }
		}
        
		public static TableSchema.Table SubSonicTest
		{
            get { return DataService.GetSchema("SubSonicTests", "Northwind"); }
		}
        
		public static TableSchema.Table Supplier
		{
            get { return DataService.GetSchema("Suppliers", "Northwind"); }
		}
        
		public static TableSchema.Table Territory
		{
            get { return DataService.GetSchema("Territories", "Northwind"); }
		}
        
	
    }
    #endregion
    #region View Struct
    public partial struct Views 
    {
		
		public static readonly string AlphabeticalListOfProduct = @"Alphabetical list of products";
        
		public static readonly string CategorySalesFor1997 = @"Category Sales for 1997";
        
		public static readonly string CurrentProductList = @"Current Product List";
        
		public static readonly string CustomerAndSuppliersByCity = @"Customer and Suppliers by City";
        
		public static readonly string Invoice = @"Invoices";
        
		public static readonly string OrderDetailsExtended = @"Order Details Extended";
        
		public static readonly string OrderSubtotal = @"Order Subtotals";
        
		public static readonly string OrdersQry = @"Orders Qry";
        
		public static readonly string ProductSalesFor1997 = @"Product Sales for 1997";
        
		public static readonly string ProductsAboveAveragePrice = @"Products Above Average Price";
        
		public static readonly string ProductsByCategory = @"Products by Category";
        
		public static readonly string QuarterlyOrder = @"Quarterly Orders";
        
		public static readonly string SalesByCategory = @"Sales by Category";
        
		public static readonly string SalesTotalsByAmount = @"Sales Totals by Amount";
        
		public static readonly string SummaryOfSalesByQuarter = @"Summary of Sales by Quarter";
        
		public static readonly string SummaryOfSalesByYear = @"Summary of Sales by Year";
        
    }
    #endregion
    
    #region Query Factories
	public static partial class DB
	{
        public static DataProvider _provider = DataService.Providers["Northwind"];
        static ISubSonicRepository _repository;
        public static ISubSonicRepository Repository 
        {
            get 
            {
                if (_repository == null)
                    return new SubSonicRepository(_provider);
                return _repository; 
            }
            set { _repository = value; }
        }
        public static Select SelectAllColumnsFrom<T>() where T : RecordBase<T>, new()
	    {
            return Repository.SelectAllColumnsFrom<T>();
	    }
	    public static Select Select()
	    {
            return Repository.Select();
	    }
	    
		public static Select Select(params string[] columns)
		{
            return Repository.Select(columns);
        }
	    
		public static Select Select(params Aggregate[] aggregates)
		{
            return Repository.Select(aggregates);
        }
   
	    public static Update Update<T>() where T : RecordBase<T>, new()
	    {
            return Repository.Update<T>();
	    }
	    
	    public static Insert Insert()
	    {
            return Repository.Insert();
	    }
	    
	    public static Delete Delete()
	    {
            return Repository.Delete();
	    }
	    
	    public static InlineQuery Query()
	    {
            return Repository.Query();
	    }
	    	    
	    
	}
    #endregion
    
}
// <auto-generated />
namespace Southwind
{
	#region Tables Struct
	public partial struct Tables
	{
		
		public static readonly string Category = @"categories";
        
		public static readonly string Customercustomerdemo = @"customercustomerdemo";
        
		public static readonly string Customerdemographic = @"customerdemographics";
        
		public static readonly string Customer = @"customers";
        
		public static readonly string Employee = @"employees";
        
		public static readonly string Employeeterritory = @"employeeterritories";
        
		public static readonly string OrderDetail = @"order details";
        
		public static readonly string Order = @"orders";
        
		public static readonly string Product = @"products";
        
		public static readonly string Region = @"region";
        
		public static readonly string Shipper = @"shippers";
        
		public static readonly string Subsonictest = @"subsonictests";
        
		public static readonly string Supplier = @"suppliers";
        
		public static readonly string Territory = @"territories";
        
	}
	#endregion
    #region Schemas
    public partial class Schemas {
		
		public static TableSchema.Table Category
		{
            get { return DataService.GetSchema("categories", "Southwind"); }
		}
        
		public static TableSchema.Table Customercustomerdemo
		{
            get { return DataService.GetSchema("customercustomerdemo", "Southwind"); }
		}
        
		public static TableSchema.Table Customerdemographic
		{
            get { return DataService.GetSchema("customerdemographics", "Southwind"); }
		}
        
		public static TableSchema.Table Customer
		{
            get { return DataService.GetSchema("customers", "Southwind"); }
		}
        
		public static TableSchema.Table Employee
		{
            get { return DataService.GetSchema("employees", "Southwind"); }
		}
        
		public static TableSchema.Table Employeeterritory
		{
            get { return DataService.GetSchema("employeeterritories", "Southwind"); }
		}
        
		public static TableSchema.Table OrderDetail
		{
            get { return DataService.GetSchema("order details", "Southwind"); }
		}
        
		public static TableSchema.Table Order
		{
            get { return DataService.GetSchema("orders", "Southwind"); }
		}
        
		public static TableSchema.Table Product
		{
            get { return DataService.GetSchema("products", "Southwind"); }
		}
        
		public static TableSchema.Table Region
		{
            get { return DataService.GetSchema("region", "Southwind"); }
		}
        
		public static TableSchema.Table Shipper
		{
            get { return DataService.GetSchema("shippers", "Southwind"); }
		}
        
		public static TableSchema.Table Subsonictest
		{
            get { return DataService.GetSchema("subsonictests", "Southwind"); }
		}
        
		public static TableSchema.Table Supplier
		{
            get { return DataService.GetSchema("suppliers", "Southwind"); }
		}
        
		public static TableSchema.Table Territory
		{
            get { return DataService.GetSchema("territories", "Southwind"); }
		}
        
	
    }
    #endregion
    #region View Struct
    public partial struct Views 
    {
		
		public static readonly string AlphabeticalListOfProduct = @"alphabetical list of products";
        
		public static readonly string CategorySalesFor1997 = @"category sales for 1997";
        
		public static readonly string CurrentProductList = @"current product list";
        
		public static readonly string CustomerAndSuppliersByCity = @"customer and suppliers by city";
        
		public static readonly string Invoice = @"invoices";
        
		public static readonly string OrderDetailsExtended = @"order details extended";
        
		public static readonly string OrderSubtotal = @"order subtotals";
        
		public static readonly string OrdersQry = @"orders qry";
        
		public static readonly string ProductSalesFor1997 = @"product sales for 1997";
        
		public static readonly string ProductsAboveAveragePrice = @"products above average price";
        
		public static readonly string ProductsByCategory = @"products by category";
        
		public static readonly string QuarterlyOrder = @"quarterly orders";
        
		public static readonly string SalesByCategory = @"sales by category";
        
		public static readonly string SalesTotalsByAmount = @"sales totals by amount";
        
		public static readonly string SummaryOfSalesByQuarter = @"summary of sales by quarter";
        
		public static readonly string SummaryOfSalesByYear = @"summary of sales by year";
        
    }
    #endregion
    
    #region Query Factories
	public static partial class DB
	{
        public static DataProvider _provider = DataService.Providers["Southwind"];
        static ISubSonicRepository _repository;
        public static ISubSonicRepository Repository 
        {
            get 
            {
                if (_repository == null)
                    return new SubSonicRepository(_provider);
                return _repository; 
            }
            set { _repository = value; }
        }
        public static Select SelectAllColumnsFrom<T>() where T : RecordBase<T>, new()
	    {
            return Repository.SelectAllColumnsFrom<T>();
	    }
	    public static Select Select()
	    {
            return Repository.Select();
	    }
	    
		public static Select Select(params string[] columns)
		{
            return Repository.Select(columns);
        }
	    
		public static Select Select(params Aggregate[] aggregates)
		{
            return Repository.Select(aggregates);
        }
   
	    public static Update Update<T>() where T : RecordBase<T>, new()
	    {
            return Repository.Update<T>();
	    }
	    
	    public static Insert Insert()
	    {
            return Repository.Insert();
	    }
	    
	    public static Delete Delete()
	    {
            return Repository.Delete();
	    }
	    
	    public static InlineQuery Query()
	    {
            return Repository.Query();
	    }
	    	    
	    
	}
    #endregion
    
}
// <auto-generated />
namespace NorthwindRepository
{
	#region Tables Struct
	public partial struct Tables
	{
		
		public static readonly string Category = @"Categories";
        
		public static readonly string CustomerCustomerDemo = @"CustomerCustomerDemo";
        
		public static readonly string CustomerDemographic = @"CustomerDemographics";
        
		public static readonly string Customer = @"Customers";
        
		public static readonly string Employee = @"Employees";
        
		public static readonly string EmployeeTerritory = @"EmployeeTerritories";
        
		public static readonly string OrderDetail = @"Order Details";
        
		public static readonly string Order = @"Orders";
        
		public static readonly string Product = @"Products";
        
		public static readonly string Region = @"Region";
        
		public static readonly string Shipper = @"Shippers";
        
		public static readonly string SubSonicTest = @"SubSonicTests";
        
		public static readonly string Supplier = @"Suppliers";
        
		public static readonly string Territory = @"Territories";
        
	}
	#endregion
    #region Schemas
    public partial class Schemas {
		
		public static TableSchema.Table Category
		{
            get { return DataService.GetSchema("Categories", "NorthwindRepository"); }
		}
        
		public static TableSchema.Table CustomerCustomerDemo
		{
            get { return DataService.GetSchema("CustomerCustomerDemo", "NorthwindRepository"); }
		}
        
		public static TableSchema.Table CustomerDemographic
		{
            get { return DataService.GetSchema("CustomerDemographics", "NorthwindRepository"); }
		}
        
		public static TableSchema.Table Customer
		{
            get { return DataService.GetSchema("Customers", "NorthwindRepository"); }
		}
        
		public static TableSchema.Table Employee
		{
            get { return DataService.GetSchema("Employees", "NorthwindRepository"); }
		}
        
		public static TableSchema.Table EmployeeTerritory
		{
            get { return DataService.GetSchema("EmployeeTerritories", "NorthwindRepository"); }
		}
        
		public static TableSchema.Table OrderDetail
		{
            get { return DataService.GetSchema("Order Details", "NorthwindRepository"); }
		}
        
		public static TableSchema.Table Order
		{
            get { return DataService.GetSchema("Orders", "NorthwindRepository"); }
		}
        
		public static TableSchema.Table Product
		{
            get { return DataService.GetSchema("Products", "NorthwindRepository"); }
		}
        
		public static TableSchema.Table Region
		{
            get { return DataService.GetSchema("Region", "NorthwindRepository"); }
		}
        
		public static TableSchema.Table Shipper
		{
            get { return DataService.GetSchema("Shippers", "NorthwindRepository"); }
		}
        
		public static TableSchema.Table SubSonicTest
		{
            get { return DataService.GetSchema("SubSonicTests", "NorthwindRepository"); }
		}
        
		public static TableSchema.Table Supplier
		{
            get { return DataService.GetSchema("Suppliers", "NorthwindRepository"); }
		}
        
		public static TableSchema.Table Territory
		{
            get { return DataService.GetSchema("Territories", "NorthwindRepository"); }
		}
        
	
    }
    #endregion
    #region View Struct
    public partial struct Views 
    {
		
		public static readonly string AlphabeticalListOfProduct = @"Alphabetical list of products";
        
		public static readonly string CategorySalesFor1997 = @"Category Sales for 1997";
        
		public static readonly string CurrentProductList = @"Current Product List";
        
		public static readonly string CustomerAndSuppliersByCity = @"Customer and Suppliers by City";
        
		public static readonly string Invoice = @"Invoices";
        
		public static readonly string OrderDetailsExtended = @"Order Details Extended";
        
		public static readonly string OrderSubtotal = @"Order Subtotals";
        
		public static readonly string OrdersQry = @"Orders Qry";
        
		public static readonly string ProductSalesFor1997 = @"Product Sales for 1997";
        
		public static readonly string ProductsAboveAveragePrice = @"Products Above Average Price";
        
		public static readonly string ProductsByCategory = @"Products by Category";
        
		public static readonly string QuarterlyOrder = @"Quarterly Orders";
        
		public static readonly string SalesByCategory = @"Sales by Category";
        
		public static readonly string SalesTotalsByAmount = @"Sales Totals by Amount";
        
		public static readonly string SummaryOfSalesByQuarter = @"Summary of Sales by Quarter";
        
		public static readonly string SummaryOfSalesByYear = @"Summary of Sales by Year";
        
    }
    #endregion
    
    #region Query Factories
	public static partial class DB
	{
        public static DataProvider _provider = DataService.Providers["NorthwindRepository"];
        static ISubSonicRepository _repository;
        public static ISubSonicRepository Repository 
        {
            get 
            {
                if (_repository == null)
                    return new SubSonicRepository(_provider);
                return _repository; 
            }
            set { _repository = value; }
        }
        public static Select SelectAllColumnsFrom<T>() where T : RecordBase<T>, new()
	    {
            return Repository.SelectAllColumnsFrom<T>();
	    }
	    public static Select Select()
	    {
            return Repository.Select();
	    }
	    
		public static Select Select(params string[] columns)
		{
            return Repository.Select(columns);
        }
	    
		public static Select Select(params Aggregate[] aggregates)
		{
            return Repository.Select(aggregates);
        }
   
	    public static Update Update<T>() where T : RecordBase<T>, new()
	    {
            return Repository.Update<T>();
	    }
	    
	    public static Insert Insert()
	    {
            return Repository.Insert();
	    }
	    
	    public static Delete Delete()
	    {
            return Repository.Delete();
	    }
	    
	    public static InlineQuery Query()
	    {
            return Repository.Query();
	    }
	    	    
	    
	    #region Repository Compliance
	    
        public static T Get<T>(object primaryKeyValue) where T : RepositoryRecord<T>, new() 
        {
            return Repository.Get<T>(primaryKeyValue);
        }
        public static T Get<T>(string columnName, object columnValue) where T : RepositoryRecord<T>, new()
        {
            return Repository.Get<T>(columnName,columnValue);
        }
        
        public static void Delete<T>(string columnName, object columnValue) where T : RepositoryRecord<T>, new() 
        {
            Repository.Delete<T>(columnName, columnValue);            
        }
        public static void Delete<T>(RepositoryRecord<T> item) where T : RepositoryRecord<T>, new() 
        {
            Repository.Delete<T>(item);
        }
        public static void DeleteByKey<T>(object itemId) where T : RepositoryRecord<T>, new() 
        {
            Repository.DeleteByKey<T>(itemId);
        }
        public static void Destroy<T>(RepositoryRecord<T> item) where T : RepositoryRecord<T>, new() 
        {
            Repository.Destroy<T>(item);
        }
        
        public static void Destroy<T>(string columnName, object value) where T : RepositoryRecord<T>, new() 
        {
            Repository.Destroy<T>(columnName,value);
        }
        public static void DestroyByKey<T>(object itemId) where T : RepositoryRecord<T>, new() 
        {
            Repository.DestroyByKey<T>(itemId);
        }
        public static int Save<T>(RepositoryRecord<T> item) where T : RepositoryRecord<T>, new() 
        {
            return Repository.Save<T>(item);
        }
        
        public static int Save<T>(RepositoryRecord<T> item, string userName) where T : RepositoryRecord<T>, new()
        {
            return Repository.Save<T>(item,userName);
        }
        public static int SaveAll<ItemType, ListType>(RepositoryList<ItemType, ListType> itemList)
          where ItemType : RepositoryRecord<ItemType>, new()
          where ListType : RepositoryList<ItemType, ListType>, new()
        {
            return Repository.SaveAll<ItemType, ListType>(itemList);
        }
 
        public static int SaveAll<ItemType, ListType>(RepositoryList<ItemType, ListType> itemList, string userName)
          where ItemType : RepositoryRecord<ItemType>, new()
          where ListType : RepositoryList<ItemType, ListType>, new()
        {
            return Repository.SaveAll<ItemType, ListType>(itemList, userName);
        }
        public static int Update<T>(RepositoryRecord<T> item) where T : RepositoryRecord<T>, new() 
        {
            return Repository.Update<T>(item, "");
        }
        public static int Update<T>(RepositoryRecord<T> item, string userName) where T : RepositoryRecord<T>, new() 
        {
            return Repository.Update<T>(item, userName);
        }
        public static int Insert<T>(RepositoryRecord<T> item) where T : RepositoryRecord<T>, new() 
        {
            return Repository.Insert<T>(item);
        }
        public static int Insert<T>(RepositoryRecord<T> item, string userName) where T : RepositoryRecord<T>, new() 
        {
            return Repository.Insert<T>(item,userName);
        }
	    #endregion
        
	}
    #endregion
    
}
// <auto-generated />
namespace SouthwindRepository
{
	#region Tables Struct
	public partial struct Tables
	{
		
		public static readonly string Category = @"categories";
        
		public static readonly string Customercustomerdemo = @"customercustomerdemo";
        
		public static readonly string Customerdemographic = @"customerdemographics";
        
		public static readonly string Customer = @"customers";
        
		public static readonly string Employee = @"employees";
        
		public static readonly string Employeeterritory = @"employeeterritories";
        
		public static readonly string OrderDetail = @"order details";
        
		public static readonly string Order = @"orders";
        
		public static readonly string Product = @"products";
        
		public static readonly string Region = @"region";
        
		public static readonly string Shipper = @"shippers";
        
		public static readonly string Subsonictest = @"subsonictests";
        
		public static readonly string Supplier = @"suppliers";
        
		public static readonly string Territory = @"territories";
        
	}
	#endregion
    #region Schemas
    public partial class Schemas {
		
		public static TableSchema.Table Category
		{
            get { return DataService.GetSchema("categories", "SouthwindRepository"); }
		}
        
		public static TableSchema.Table Customercustomerdemo
		{
            get { return DataService.GetSchema("customercustomerdemo", "SouthwindRepository"); }
		}
        
		public static TableSchema.Table Customerdemographic
		{
            get { return DataService.GetSchema("customerdemographics", "SouthwindRepository"); }
		}
        
		public static TableSchema.Table Customer
		{
            get { return DataService.GetSchema("customers", "SouthwindRepository"); }
		}
        
		public static TableSchema.Table Employee
		{
            get { return DataService.GetSchema("employees", "SouthwindRepository"); }
		}
        
		public static TableSchema.Table Employeeterritory
		{
            get { return DataService.GetSchema("employeeterritories", "SouthwindRepository"); }
		}
        
		public static TableSchema.Table OrderDetail
		{
            get { return DataService.GetSchema("order details", "SouthwindRepository"); }
		}
        
		public static TableSchema.Table Order
		{
            get { return DataService.GetSchema("orders", "SouthwindRepository"); }
		}
        
		public static TableSchema.Table Product
		{
            get { return DataService.GetSchema("products", "SouthwindRepository"); }
		}
        
		public static TableSchema.Table Region
		{
            get { return DataService.GetSchema("region", "SouthwindRepository"); }
		}
        
		public static TableSchema.Table Shipper
		{
            get { return DataService.GetSchema("shippers", "SouthwindRepository"); }
		}
        
		public static TableSchema.Table Subsonictest
		{
            get { return DataService.GetSchema("subsonictests", "SouthwindRepository"); }
		}
        
		public static TableSchema.Table Supplier
		{
            get { return DataService.GetSchema("suppliers", "SouthwindRepository"); }
		}
        
		public static TableSchema.Table Territory
		{
            get { return DataService.GetSchema("territories", "SouthwindRepository"); }
		}
        
	
    }
    #endregion
    #region View Struct
    public partial struct Views 
    {
		
		public static readonly string AlphabeticalListOfProduct = @"alphabetical list of products";
        
		public static readonly string CategorySalesFor1997 = @"category sales for 1997";
        
		public static readonly string CurrentProductList = @"current product list";
        
		public static readonly string CustomerAndSuppliersByCity = @"customer and suppliers by city";
        
		public static readonly string Invoice = @"invoices";
        
		public static readonly string OrderDetailsExtended = @"order details extended";
        
		public static readonly string OrderSubtotal = @"order subtotals";
        
		public static readonly string OrdersQry = @"orders qry";
        
		public static readonly string ProductSalesFor1997 = @"product sales for 1997";
        
		public static readonly string ProductsAboveAveragePrice = @"products above average price";
        
		public static readonly string ProductsByCategory = @"products by category";
        
		public static readonly string QuarterlyOrder = @"quarterly orders";
        
		public static readonly string SalesByCategory = @"sales by category";
        
		public static readonly string SalesTotalsByAmount = @"sales totals by amount";
        
		public static readonly string SummaryOfSalesByQuarter = @"summary of sales by quarter";
        
		public static readonly string SummaryOfSalesByYear = @"summary of sales by year";
        
    }
    #endregion
    
    #region Query Factories
	public static partial class DB
	{
        public static DataProvider _provider = DataService.Providers["SouthwindRepository"];
        static ISubSonicRepository _repository;
        public static ISubSonicRepository Repository 
        {
            get 
            {
                if (_repository == null)
                    return new SubSonicRepository(_provider);
                return _repository; 
            }
            set { _repository = value; }
        }
        public static Select SelectAllColumnsFrom<T>() where T : RecordBase<T>, new()
	    {
            return Repository.SelectAllColumnsFrom<T>();
	    }
	    public static Select Select()
	    {
            return Repository.Select();
	    }
	    
		public static Select Select(params string[] columns)
		{
            return Repository.Select(columns);
        }
	    
		public static Select Select(params Aggregate[] aggregates)
		{
            return Repository.Select(aggregates);
        }
   
	    public static Update Update<T>() where T : RecordBase<T>, new()
	    {
            return Repository.Update<T>();
	    }
	    
	    public static Insert Insert()
	    {
            return Repository.Insert();
	    }
	    
	    public static Delete Delete()
	    {
            return Repository.Delete();
	    }
	    
	    public static InlineQuery Query()
	    {
            return Repository.Query();
	    }
	    	    
	    
	    #region Repository Compliance
	    
        public static T Get<T>(object primaryKeyValue) where T : RepositoryRecord<T>, new() 
        {
            return Repository.Get<T>(primaryKeyValue);
        }
        public static T Get<T>(string columnName, object columnValue) where T : RepositoryRecord<T>, new()
        {
            return Repository.Get<T>(columnName,columnValue);
        }
        
        public static void Delete<T>(string columnName, object columnValue) where T : RepositoryRecord<T>, new() 
        {
            Repository.Delete<T>(columnName, columnValue);            
        }
        public static void Delete<T>(RepositoryRecord<T> item) where T : RepositoryRecord<T>, new() 
        {
            Repository.Delete<T>(item);
        }
        public static void DeleteByKey<T>(object itemId) where T : RepositoryRecord<T>, new() 
        {
            Repository.DeleteByKey<T>(itemId);
        }
        public static void Destroy<T>(RepositoryRecord<T> item) where T : RepositoryRecord<T>, new() 
        {
            Repository.Destroy<T>(item);
        }
        
        public static void Destroy<T>(string columnName, object value) where T : RepositoryRecord<T>, new() 
        {
            Repository.Destroy<T>(columnName,value);
        }
        public static void DestroyByKey<T>(object itemId) where T : RepositoryRecord<T>, new() 
        {
            Repository.DestroyByKey<T>(itemId);
        }
        public static int Save<T>(RepositoryRecord<T> item) where T : RepositoryRecord<T>, new() 
        {
            return Repository.Save<T>(item);
        }
        
        public static int Save<T>(RepositoryRecord<T> item, string userName) where T : RepositoryRecord<T>, new()
        {
            return Repository.Save<T>(item,userName);
        }
        public static int SaveAll<ItemType, ListType>(RepositoryList<ItemType, ListType> itemList)
          where ItemType : RepositoryRecord<ItemType>, new()
          where ListType : RepositoryList<ItemType, ListType>, new()
        {
            return Repository.SaveAll<ItemType, ListType>(itemList);
        }
 
        public static int SaveAll<ItemType, ListType>(RepositoryList<ItemType, ListType> itemList, string userName)
          where ItemType : RepositoryRecord<ItemType>, new()
          where ListType : RepositoryList<ItemType, ListType>, new()
        {
            return Repository.SaveAll<ItemType, ListType>(itemList, userName);
        }
        public static int Update<T>(RepositoryRecord<T> item) where T : RepositoryRecord<T>, new() 
        {
            return Repository.Update<T>(item, "");
        }
        public static int Update<T>(RepositoryRecord<T> item, string userName) where T : RepositoryRecord<T>, new() 
        {
            return Repository.Update<T>(item, userName);
        }
        public static int Insert<T>(RepositoryRecord<T> item) where T : RepositoryRecord<T>, new() 
        {
            return Repository.Insert<T>(item);
        }
        public static int Insert<T>(RepositoryRecord<T> item, string userName) where T : RepositoryRecord<T>, new() 
        {
            return Repository.Insert<T>(item,userName);
        }
	    #endregion
        
	}
    #endregion
    
}
#region Databases
public partial struct Databases 
{
	
	public static readonly string Northwind = @"Northwind";
    
	public static readonly string Southwind = @"Southwind";
    
	public static readonly string NorthwindRepository = @"NorthwindRepository";
    
	public static readonly string SouthwindRepository = @"SouthwindRepository";
    
}
#endregion