using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Southwind
{
    /// <summary>
    /// Controller class for customerdemographics
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class CustomerdemographicController
    {
        // Preload our schema..
        Customerdemographic thisSchemaLoad = new Customerdemographic();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public CustomerdemographicCollection FetchAll()
        {
            CustomerdemographicCollection coll = new CustomerdemographicCollection();
            Query qry = new Query(Customerdemographic.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public CustomerdemographicCollection FetchByID(object CustomerTypeID)
        {
            CustomerdemographicCollection coll = new CustomerdemographicCollection().Where("CustomerTypeID", CustomerTypeID).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public CustomerdemographicCollection FetchByQuery(Query qry)
        {
            CustomerdemographicCollection coll = new CustomerdemographicCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object CustomerTypeID)
        {
            return (Customerdemographic.Delete(CustomerTypeID) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object CustomerTypeID)
        {
            return (Customerdemographic.Destroy(CustomerTypeID) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string CustomerTypeID,string CustomerDesc)
	    {
		    Customerdemographic item = new Customerdemographic();
		    
            item.CustomerTypeID = CustomerTypeID;
            
            item.CustomerDesc = CustomerDesc;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(string CustomerTypeID,string CustomerDesc)
	    {
		    Customerdemographic item = new Customerdemographic();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.CustomerTypeID = CustomerTypeID;
				
			item.CustomerDesc = CustomerDesc;
				
	        item.Save(UserName);
	    }
    }
}
